version: "3.8"
services:
  redis:
    image: redis:6.2-alpine
    restart: "no"
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --requirepass password --loglevel warning

  subscriber:
    build: ./subscriber .
    volumes:
      - ./subscriber:/usr/app
    ports:
      - "3003:3003"
    command: npm start

  publisher:
    build: ./publisher .
    volumes:
      - ./publisher:/usr/app
    ports:
      - "3000:3000"
    command: npm start
